### ISSUE TITLE
Recognize closed DB connections and reopen as needed

### ISSUE THREAD

**Issue by Myatu** [mricon/totp-cgi#25]
Noticed that there's no automatic re-connect in the FCGI version of totpcgi when the MySQL server has closed the connection:

```
Jan 12 16:58:51 cam totp.fcgi[24560]: Failure: user=redacted, mode=PAM_SM_AUTH, host=redacted, message=(2006, 'MySQL server has gone away')
Jan 12 16:58:51 cam sshd[26300]: pam_url(sshd:auth): The requested URL returned error: 400
```

**Comment by olorin** [comment]
@mricon looks like this was fixed in 11cd3e9ee9d6db0087939a8a1bc9d7ac0f435dd8; can this issue be closed?
