### ISSUE TITLE
selinux policy fails on Fedora 21 and newer

### ISSUE THREAD

**Issue by tyll** [mricon/totp-cgi#27]
Errors:

    + make NAME=mls -f /usr/share/selinux/devel/Makefile
    Compiling mls totpcgi module
    totpcgi.te:55: Warning: miscfiles_read_certs() has been deprecated, please use miscfiles_read_generic_certs() instead.
    totpcgi.te:58: Warning: miscfiles_read_certs() has been deprecated, please use miscfiles_read_generic_certs() instead.
    totpcgi.te:41:ERROR 'unknown type httpd_totpcgi_script_t' at token ';' on line 5216:
            typeattribute httpd_totpcgi_script_t syslog_client_type;
    #line 41

Fedora Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1107456

**Comment by herlo** [comment]
http://pkgs.fedoraproject.org/cgit/totpcgi.git/commit/?id=2826a2e547f3d3aa6b18126e93c1574088cc6f35 <-- this apparently fixes the above bug.
